# Site settings
title: yoonu blog
email: tomorrowcho@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: 윤우 포트폴리오 "https://yoonucho.github.io/intro" # the base hostname & protocol for your site

# Sidebar settings
description: One sentence introducing yourself or what you do

# Social icons
# facebook: username
# linkedin: username
github: yoonucho
# deviantart: username
codepen: tomorrowcho

footer: © yoonu blog

# Build settings
markdown: kramdown
